name: publish

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'dry run'
        required: false
        type: boolean
        default: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '14'
      - name: Log in to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
      - name: Publish
        run: npm publish --dry-run=${{ github.event.inputs.dryRun }}
